In [81]:
import pandas as pd
import numpy as np

## Pandas - Series, DataFrame

# Series (its a class)
A collection of labelled data

In [82]:
s1 = pd.Series([1,2,3,4], index= ['A','B','C','D'])
s1

A    1
B    2
C    3
D    4
dtype: int64

In [83]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [84]:
s2 = pd.Series([10,20,30,40])
s2

0    10
1    20
2    30
3    40
dtype: int64

In [85]:
players = pd.Series(["Dhoni","Kohli","Gill"])
players

0    Dhoni
1    Kohli
2     Gill
dtype: str

## Different ways to create Series

In [86]:
arr1 = np.arange(21,30)
s1 = pd.Series(arr1)
s1
#1st

0    21
1    22
2    23
3    24
4    25
5    26
6    27
7    28
8    29
dtype: int64

In [87]:
toppers = pd.Series({"Maths":89, "Chem":90, "Phy":70})
toppers
#2nd

Maths    89
Chem     90
Phy      70
dtype: int64

In [88]:
## Operations on Series

In [89]:
s1 = pd.Series(np.arange(21,26))
s2 = pd.Series(np.arange(16,21))

In [90]:
s1

0    21
1    22
2    23
3    24
4    25
dtype: int64

In [91]:
s2

0    16
1    17
2    18
3    19
4    20
dtype: int64

In [92]:
s3 = s1 + s2
s3

0    37
1    39
2    41
3    43
4    45
dtype: int64

In [93]:
s1 = pd.Series(np.arange(21,26), index= ['A','B','C','D','E'])
s2 = pd.Series(np.arange(16,21), index= ['D','E','F','G','H'])

In [94]:
s1

A    21
B    22
C    23
D    24
E    25
dtype: int64

In [95]:
s2

D    16
E    17
F    18
G    19
H    20
dtype: int64

In [96]:
s1 + s2
#values with same index will only be added

A     NaN
B     NaN
C     NaN
D    40.0
E    42.0
F     NaN
G     NaN
H     NaN
dtype: float64

In [97]:
s1 = pd.Series(np.random.randint(1,25,7))
s1

0     8
1    22
2    10
3    21
4    23
5     3
6    13
dtype: int32

In [98]:
s1.index = ['x1','x2','x3','x4','x5','x6','x7']
s1
#we can later change the index

x1     8
x2    22
x3    10
x4    21
x5    23
x6     3
x7    13
dtype: int32

In [99]:
s1['x5']
#retreiving element using labelled index

np.int32(23)

In [100]:
s1.iloc[2]
#retreiving element using internal index

np.int32(10)

In [101]:
s1[s1 % 2 == 0]

x1     8
x2    22
x3    10
dtype: int32

In [102]:
s1.min()

np.int32(3)

In [103]:
s1.max()

np.int32(23)

In [104]:
s1.mean()

np.float64(14.285714285714286)

In [105]:
s1.mode()

0     3
1     8
2    10
3    13
4    21
5    22
6    23
dtype: int32

In [106]:
s1.sum()

np.int64(100)

In [107]:
s1[s1 > s1['x1']]
#find the elements greater than element at index x1

x2    22
x3    10
x4    21
x5    23
x7    13
dtype: int32

# DataFrame  (It is a class)

In [108]:
s1 = pd.Series([1,2,3,4])
s2 = pd.Series([11,12,13,14])
df = pd.DataFrame([s1,s2])
df

    0   1   2   3
0   1   2   3   4
1  11  12  13  14

In [109]:
df.index = ['i1','i2']
df

     0   1   2   3
i1   1   2   3   4
i2  11  12  13  14

In [110]:
df.columns = ['c1','c2','c3','c4']
df

    c1  c2  c3  c4
i1   1   2   3   4
i2  11  12  13  14

In [111]:
type(df)

pandas.DataFrame

In [112]:
type(df['c1'])

pandas.Series

In [113]:
df.shape

(2, 4)

In [114]:
df.ndim

2

In [115]:
df.size

8

## Different ways to create DataFrame

In [116]:
df1 = pd.DataFrame(np.arange(1,26).reshape(5,5))                
df1      
#1st

    0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25

In [117]:
df2 = pd.DataFrame([s1,s2])
df2
#2nd

    0   1   2   3
0   1   2   3   4
1  11  12  13  14

In [118]:
employee = pd.DataFrame([[101,"Geetanjali",23000],
                         [102,"Mayur",34000],
                         [103,"Ashwini",25000]],
                        columns = ['Eid', 'Name', 'Salary'],
                        index = ['#1','#2','#3'])
employee    
#row-wise

    Eid        Name  Salary
#1  101  Geetanjali   23000
#2  102       Mayur   34000
#3  103     Ashwini   25000

In [119]:
students = pd.DataFrame({"Rollno":[1,2,3,4],
                         "Name":["Ram","Shyam","Geeta","Seeta"],
                         "Marks":[45,78,40,30]})
students
#column-wise

   Rollno   Name  Marks
0       1    Ram     45
1       2  Shyam     78
2       3  Geeta     40
3       4  Seeta     30

In [120]:
students.columns

Index(['Rollno', 'Name', 'Marks'], dtype='str')

## Adding or removing column/row

In [121]:
intake = pd.DataFrame({'Seats':[60,120,120],
                       'Admitted':[55,110,118]},
                      index = ["Mech","IT","ENTC"])
intake

      Seats  Admitted
Mech     60        55
IT      120       110
ENTC    120       118

In [122]:
intake['Available'] = intake['Seats'] - intake['Admitted']
intake
#add another column using existing columns

      Seats  Admitted  Available
Mech     60        55          5
IT      120       110         10
ENTC    120       118          2

In [123]:
employee

    Eid        Name  Salary
#1  101  Geetanjali   23000
#2  102       Mayur   34000
#3  103     Ashwini   25000

In [124]:
employee['Gender'] = ['F','M','F']
employee
#seperately add another column

    Eid        Name  Salary Gender
#1  101  Geetanjali   23000      F
#2  102       Mayur   34000      M
#3  103     Ashwini   25000      F

In [125]:
employee.loc[3] = [104,"Sakshi",26000,'F']
employee
#adding row in DataFrame

    Eid        Name  Salary Gender
#1  101  Geetanjali   23000      F
#2  102       Mayur   34000      M
#3  103     Ashwini   25000      F
3   104      Sakshi   26000      F

In [126]:
employee.loc[employee.shape[0]] = [105, "Rajashree", 34000, 'F']

In [127]:
employee['Address'] = ['Pune', 'Mumbai', 'Pune', 'Nashik', 'Pune']

In [128]:
employee['Dno'] = [1,2,1, np.nan, 3]

In [129]:
employee['Annual Salary'] = employee['Salary']*12
employee

    Eid        Name  Salary Gender Address  Dno  Annual Salary
#1  101  Geetanjali   23000      F    Pune  1.0         276000
#2  102       Mayur   34000      M  Mumbai  2.0         408000
#3  103     Ashwini   25000      F    Pune  1.0         300000
3   104      Sakshi   26000      F  Nashik  NaN         312000
4   105   Rajashree   34000      F    Pune  3.0         408000

In [130]:
employee.drop('Annual Salary',axis = 1)

    Eid        Name  Salary Gender Address  Dno
#1  101  Geetanjali   23000      F    Pune  1.0
#2  102       Mayur   34000      M  Mumbai  2.0
#3  103     Ashwini   25000      F    Pune  1.0
3   104      Sakshi   26000      F  Nashik  NaN
4   105   Rajashree   34000      F    Pune  3.0

In [131]:
#emp1 = employee.drop('Annual Salary',axis = 1)
employee.drop('Annual Salary',axis = 1, inplace = True)

### Using inplace you can permanently delete the column using axis=1

In [132]:
employee.drop(1, inplace = True)
employee
#to drop row

KeyError: '[1] not found in axis'

# Selection

In [133]:
df1.columns = ['A', 'B', 'C', 'D', 'E']
df1.index = ['i1','i2','i3','i4','i5']
df1

     A   B   C   D   E
i1   1   2   3   4   5
i2   6   7   8   9  10
i3  11  12  13  14  15
i4  16  17  18  19  20
i5  21  22  23  24  25

In [134]:
df1['C']

i1     3
i2     8
i3    13
i4    18
i5    23
Name: C, dtype: int64

In [135]:
df1[['B','C']]
#two brackets for retrieving 2 or more columns

     B   C
i1   2   3
i2   7   8
i3  12  13
i4  17  18
i5  22  23

In [136]:
df1.loc['i1']

A    1
B    2
C    3
D    4
E    5
Name: i1, dtype: int64

#### df[colname]
df.loc[index]

In [137]:
df1.loc[['i1', 'i4']]

     A   B   C   D   E
i1   1   2   3   4   5
i4  16  17  18  19  20

In [138]:
df1.loc['i1', ['B','C','D']]
#to retrieve inbetween elements

B    2
C    3
D    4
Name: i1, dtype: int64

In [139]:
df1.loc[['i2','i3','i4'], ['A','B']]

     A   B
i2   6   7
i3  11  12
i4  16  17

In [140]:
df1.loc[['i1','i2','i5'], ['D','E']]

     D   E
i1   4   5
i2   9  10
i5  24  25

In [141]:
employee.reset_index(inplace = True)
#resets the index but adds old index as a column

In [142]:
employee

  index  Eid        Name  Salary Gender Address  Dno
0    #1  101  Geetanjali   23000      F    Pune  1.0
1    #2  102       Mayur   34000      M  Mumbai  2.0
2    #3  103     Ashwini   25000      F    Pune  1.0
3     3  104      Sakshi   26000      F  Nashik  NaN
4     4  105   Rajashree   34000      F    Pune  3.0

In [143]:
employee.drop('index', axis = 1, inplace = True)
employee
#dropping index column

   Eid        Name  Salary Gender Address  Dno
0  101  Geetanjali   23000      F    Pune  1.0
1  102       Mayur   34000      M  Mumbai  2.0
2  103     Ashwini   25000      F    Pune  1.0
3  104      Sakshi   26000      F  Nashik  NaN
4  105   Rajashree   34000      F    Pune  3.0

In [144]:
employee.iloc[2]
#iloc for default index

Eid            103
Name       Ashwini
Salary       25000
Gender           F
Address       Pune
Dno            1.0
Name: 2, dtype: object

In [145]:
#employee.loc[employee.shape[0]] = [106, "Parth", 30000, 'M', "Mumbai", 2]

In [146]:
employee

   Eid        Name  Salary Gender Address  Dno
0  101  Geetanjali   23000      F    Pune  1.0
1  102       Mayur   34000      M  Mumbai  2.0
2  103     Ashwini   25000      F    Pune  1.0
3  104      Sakshi   26000      F  Nashik  NaN
4  105   Rajashree   34000      F    Pune  3.0

In [147]:
employee[employee['Name'] == 'Ashwini']
#conditional selection

   Eid     Name  Salary Gender Address  Dno
2  103  Ashwini   25000      F    Pune  1.0

In [148]:
employee[employee['Salary'] > 30000]

   Eid       Name  Salary Gender Address  Dno
1  102      Mayur   34000      M  Mumbai  2.0
4  105  Rajashree   34000      F    Pune  3.0

In [149]:
employee[employee['Ashwini'] == 'Pune']

KeyError: 'Ashwini'

In [ ]:
employee[(employee['Address'] == 'Pune') & (employee['Dno'] == 1)]

In [150]:
employee

   Eid        Name  Salary Gender Address  Dno
0  101  Geetanjali   23000      F    Pune  1.0
1  102       Mayur   34000      M  Mumbai  2.0
2  103     Ashwini   25000      F    Pune  1.0
3  104      Sakshi   26000      F  Nashik  NaN
4  105   Rajashree   34000      F    Pune  3.0

In [151]:
employee.loc[5] = [105, "Sakshi", 24000, 'F', "Mumbai", 2]

In [152]:
employee.loc[6] = [106, "Parth", 28000, 'M', "Mumbai", 1]

In [153]:
employee[employee['Salary'] < 25000]

   Eid        Name  Salary Gender Address  Dno
0  101  Geetanjali   23000      F    Pune  1.0
5  105      Sakshi   24000      F  Mumbai  2.0

In [154]:
employee[employee['Salary'] < 25000] [['Gender', 'Name']]
#name, gender of employees having salary < 25000

  Gender        Name
0      F  Geetanjali
5      F      Sakshi

In [155]:
employee[employee['Name'] == 'Rajshree']['Eid']

Series([], Name: Eid, dtype: int64)

In [156]:
employee.loc[employee['Name'] == 'Rajshree', 'Eid'] = 102 
#change eid of rajshree

In [157]:
employee

   Eid        Name  Salary Gender Address  Dno
0  101  Geetanjali   23000      F    Pune  1.0
1  102       Mayur   34000      M  Mumbai  2.0
2  103     Ashwini   25000      F    Pune  1.0
3  104      Sakshi   26000      F  Nashik  NaN
4  105   Rajashree   34000      F    Pune  3.0
5  105      Sakshi   24000      F  Mumbai  2.0
6  106       Parth   28000      M  Mumbai  1.0

In [159]:
employee.loc[5, 'Salary'] = 30000
#direct changes when index is known
employee

   Eid        Name  Salary Gender Address  Dno
0  101  Geetanjali   23000      F    Pune  1.0
1  102       Mayur   34000      M  Mumbai  2.0
2  103     Ashwini   25000      F    Pune  1.0
3  104      Sakshi   26000      F  Nashik  NaN
4  105   Rajashree   34000      F    Pune  3.0
5  105      Sakshi   30000      F  Mumbai  2.0
6  106       Parth   28000      M  Mumbai  1.0

In [161]:
dept = pd.DataFrame({'Dno':[1,2,3,4],
                     'Name':['IT', 'Admin', 'HR', 'SCM']})
dept

   Dno   Name
0    1     IT
1    2  Admin
2    3     HR
3    4    SCM

In [162]:
pd.concat([employee, dept])
#it combines employee and dept dataframe row wise

     Eid        Name   Salary Gender Address  Dno
0  101.0  Geetanjali  23000.0      F    Pune  1.0
1  102.0       Mayur  34000.0      M  Mumbai  2.0
2  103.0     Ashwini  25000.0      F    Pune  1.0
3  104.0      Sakshi  26000.0      F  Nashik  NaN
4  105.0   Rajashree  34000.0      F    Pune  3.0
5  105.0      Sakshi  30000.0      F  Mumbai  2.0
6  106.0       Parth  28000.0      M  Mumbai  1.0
0    NaN          IT      NaN    NaN     NaN  1.0
1    NaN       Admin      NaN    NaN     NaN  2.0
2    NaN          HR      NaN    NaN     NaN  3.0
3    NaN         SCM      NaN    NaN     NaN  4.0

In [164]:
pd.concat([employee, dept], axis=1)
#combine dataframe columnwise

   Eid        Name  Salary Gender Address  Dno  Dno   Name
0  101  Geetanjali   23000      F    Pune  1.0  1.0     IT
1  102       Mayur   34000      M  Mumbai  2.0  2.0  Admin
2  103     Ashwini   25000      F    Pune  1.0  3.0     HR
3  104      Sakshi   26000      F  Nashik  NaN  4.0    SCM
4  105   Rajashree   34000      F    Pune  3.0  NaN    NaN
5  105      Sakshi   30000      F  Mumbai  2.0  NaN    NaN
6  106       Parth   28000      M  Mumbai  1.0  NaN    NaN

### concat will not be used often

In [165]:
pd.merge(employee, dept, on = 'Dno', how = 'inner')
#it will add both dataframe on the basis on dno

   Eid      Name_x  Salary Gender Address  Dno Name_y
0  101  Geetanjali   23000      F    Pune  1.0     IT
1  102       Mayur   34000      M  Mumbai  2.0  Admin
2  103     Ashwini   25000      F    Pune  1.0     IT
3  105   Rajashree   34000      F    Pune  3.0     HR
4  105      Sakshi   30000      F  Mumbai  2.0  Admin
5  106       Parth   28000      M  Mumbai  1.0     IT

### And while merging column names of column should be same

In [167]:
pd.merge(employee, dept, on = 'Dno', how = 'left')

   Eid      Name_x  Salary Gender Address  Dno Name_y
0  101  Geetanjali   23000      F    Pune  1.0     IT
1  102       Mayur   34000      M  Mumbai  2.0  Admin
2  103     Ashwini   25000      F    Pune  1.0     IT
3  104      Sakshi   26000      F  Nashik  NaN    NaN
4  105   Rajashree   34000      F    Pune  3.0     HR
5  105      Sakshi   30000      F  Mumbai  2.0  Admin
6  106       Parth   28000      M  Mumbai  1.0     IT

In [169]:
result= pd.merge(employee, dept, on = 'Dno', how = 'left')
result #store in result variable

   Eid      Name_x  Salary Gender Address  Dno Name_y
0  101  Geetanjali   23000      F    Pune  1.0     IT
1  102       Mayur   34000      M  Mumbai  2.0  Admin
2  103     Ashwini   25000      F    Pune  1.0     IT
3  104      Sakshi   26000      F  Nashik  NaN    NaN
4  105   Rajashree   34000      F    Pune  3.0     HR
5  105      Sakshi   30000      F  Mumbai  2.0  Admin
6  106       Parth   28000      M  Mumbai  1.0     IT

In [170]:
employee['Salary'].min()

np.int64(23000)

In [171]:
employee['Salary'].max()

np.int64(34000)

In [172]:
employee['Salary'].mean()

np.float64(28571.428571428572)

In [173]:
employee['Salary'].sum()

np.int64(200000)

In [174]:
employee['Salary'].count()

np.int64(7)

In [175]:
employee['Dno'].mode()

0    1.0
Name: Dno, dtype: float64

In [176]:
employee.loc[employee['Eid'] == 106, 'Name'] = 'Mayur'
employee

   Eid        Name  Salary Gender Address  Dno
0  101  Geetanjali   23000      F    Pune  1.0
1  102       Mayur   34000      M  Mumbai  2.0
2  103     Ashwini   25000      F    Pune  1.0
3  104      Sakshi   26000      F  Nashik  NaN
4  105   Rajashree   34000      F    Pune  3.0
5  105      Sakshi   30000      F  Mumbai  2.0
6  106       Mayur   28000      M  Mumbai  1.0

In [177]:
employee['Name'].mode()

0     Mayur
1    Sakshi
Name: Name, dtype: str

In [178]:
pd.DataFrame(employee.groupby('Dno'))

     0                                                  1
0  1.0     Eid        Name  Salary Gender Address  Dno...
1  2.0     Eid    Name  Salary Gender Address  Dno
1  ...
2  3.0     Eid       Name  Salary Gender Address  Dno
...

In [179]:
employee.groupby('Dno')['Dno'].count()
#counting how many people are present in each dept

Dno
1.0    3
2.0    2
3.0    1
Name: Dno, dtype: int64

In [180]:
employee.groupby('Dno')['Salary'].sum()
#total salary based on different dept

Dno
1.0    76000
2.0    64000
3.0    34000
Name: Salary, dtype: int64

In [181]:
employee.groupby('Address')['Address'].count()

Address
Mumbai    3
Nashik    1
Pune      3
Name: Address, dtype: int64

In [182]:
employee.groupby('Gender')['Salary'].max()

Gender
F    34000
M    34000
Name: Salary, dtype: int64

In [183]:
employee['Address'].unique()
#unique will give unique values from columns

<StringArray>
['Pune', 'Mumbai', 'Nashik']
Length: 3, dtype: str

In [184]:
employee['Address'].nunique()
#nunique tells how many unique values

3

# Dataframe attributes
shape - tuple
columns - array
index - array
values - 2D array
(output)

In [185]:
employee['Address'].values

<StringArray>
['Pune', 'Mumbai', 'Pune', 'Nashik', 'Pune', 'Mumbai', 'Mumbai']
Length: 7, dtype: str

In [186]:
employee

   Eid        Name  Salary Gender Address  Dno
0  101  Geetanjali   23000      F    Pune  1.0
1  102       Mayur   34000      M  Mumbai  2.0
2  103     Ashwini   25000      F    Pune  1.0
3  104      Sakshi   26000      F  Nashik  NaN
4  105   Rajashree   34000      F    Pune  3.0
5  105      Sakshi   30000      F  Mumbai  2.0
6  106       Mayur   28000      M  Mumbai  1.0

In [187]:
employee.groupby('Address')['Address'].count()

Address
Mumbai    3
Nashik    1
Pune      3
Name: Address, dtype: int64

In [188]:
employee['Address'].value_counts()

Address
Pune      3
Mumbai    3
Nashik    1
Name: count, dtype: int64

## Value_counts()
use when we have to use count on a column and also grouping

In [189]:
employee['Gender'].value_counts()

Gender
F    5
M    2
Name: count, dtype: int64

In [191]:
employee['BG'] = ['A', 'B-', np.nan, np.nan, 'O+', 'AB+', np.nan]
employee

   Eid        Name  Salary Gender Address  Dno   BG
0  101  Geetanjali   23000      F    Pune  1.0    A
1  102       Mayur   34000      M  Mumbai  2.0   B-
2  103     Ashwini   25000      F    Pune  1.0  NaN
3  104      Sakshi   26000      F  Nashik  NaN  NaN
4  105   Rajashree   34000      F    Pune  3.0   O+
5  105      Sakshi   30000      F  Mumbai  2.0  AB+
6  106       Mayur   28000      M  Mumbai  1.0  NaN

In [192]:
employee.loc[employee['Eid'] == 101, 'Salary'] = np.nan
employee

   Eid        Name   Salary Gender Address  Dno   BG
0  101  Geetanjali      NaN      F    Pune  1.0    A
1  102       Mayur  34000.0      M  Mumbai  2.0   B-
2  103     Ashwini  25000.0      F    Pune  1.0  NaN
3  104      Sakshi  26000.0      F  Nashik  NaN  NaN
4  105   Rajashree  34000.0      F    Pune  3.0   O+
5  105      Sakshi  30000.0      F  Mumbai  2.0  AB+
6  106       Mayur  28000.0      M  Mumbai  1.0  NaN

# Handling missing values

In [193]:
employee.isna()
#to check if there is null value

     Eid   Name  Salary  Gender  Address    Dno     BG
0  False  False    True   False    False  False  False
1  False  False   False   False    False  False  False
2  False  False   False   False    False  False   True
3  False  False   False   False    False   True   True
4  False  False   False   False    False  False  False
5  False  False   False   False    False  False  False
6  False  False   False   False    False  False   True

In [195]:
employee.isna().sum()
#gives null values from every column

Eid        0
Name       0
Salary     1
Gender     0
Address    0
Dno        1
BG         3
dtype: int64

## To handle missing value
Delete column - check if important
Delete row - below 10%
Fill the missing value

In [197]:
employee.drop('BG', axis = 1) #to drop column

   Eid        Name   Salary Gender Address  Dno
0  101  Geetanjali      NaN      F    Pune  1.0
1  102       Mayur  34000.0      M  Mumbai  2.0
2  103     Ashwini  25000.0      F    Pune  1.0
3  104      Sakshi  26000.0      F  Nashik  NaN
4  105   Rajashree  34000.0      F    Pune  3.0
5  105      Sakshi  30000.0      F  Mumbai  2.0
6  106       Mayur  28000.0      M  Mumbai  1.0

In [198]:
employee.dropna()
#dropna method will delete rows with null values

   Eid       Name   Salary Gender Address  Dno   BG
1  102      Mayur  34000.0      M  Mumbai  2.0   B-
4  105  Rajashree  34000.0      F    Pune  3.0   O+
5  105     Sakshi  30000.0      F  Mumbai  2.0  AB+

In [200]:
employee.isna().sum()

Eid        0
Name       0
Salary     1
Gender     0
Address    0
Dno        1
BG         3
dtype: int64

## 1st way to fill null value

In [201]:
avg = employee['Salary'].mean()
employee.loc[employee['Salary'].isna(), 'Salary'] = avg

In [202]:
employee

   Eid        Name   Salary Gender Address  Dno   BG
0  101  Geetanjali  29500.0      F    Pune  1.0    A
1  102       Mayur  34000.0      M  Mumbai  2.0   B-
2  103     Ashwini  25000.0      F    Pune  1.0  NaN
3  104      Sakshi  26000.0      F  Nashik  NaN  NaN
4  105   Rajashree  34000.0      F    Pune  3.0   O+
5  105      Sakshi  30000.0      F  Mumbai  2.0  AB+
6  106       Mayur  28000.0      M  Mumbai  1.0  NaN

## 2nd way to fill null value

In [203]:
employee['Salary'].fillna(avg, inplace = True)
#automated method to fill null values

C:\Users\shrut\AppData\Local\Temp\ipykernel_12056\964427499.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  employee['Salary'].fillna(avg, inplace = True)

0    29500.0
1    34000.0
2    25000.0
3    26000.0
4    34000.0
5    30000.0
6    28000.0
Name: Salary, dtype: float64

### find the average salary for the dept where this employee is working and then fill